### ISSUE TITLE
MDL extension for mdl-layout__drawer needed?

### ISSUE THREAD

**Issue by steamonimo** [redpelicans/aurelia-material#9]
The mdl-layout__drawer is not working right now. It will not show the Hamburger symbol and I assume it will not open any menu on top. I wonder if this can be fixed with an MDL extension as well:

Doc:
http://www.getmdl.io/components/index.html#layout-section

Example:

```
  <div class="mdl-layout__header-row">
    <span class="mdl-layout-title">TEST-Menu</span>
    <div class="mdl-layout-spacer"></div>
    <div>
      <nav class="mdl-navigation">
          <a class="mdl-navigation__link mdl-typography--text-uppercase" href="#">Menu1</a>
      </nav>
    </div>    
  </div>

  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">TEST-Drawer</span>
    <nav class="mdl-navigation">
        <a class="mdl-navigation__link mdl-typography--text-uppercase" href="#">Drawer1</a>
    </nav>
  </div>
```

Many thanks for your Plugin and Example. This is very helpful for learning about Aurelia.

**Comment by a2bsoftware** [comment]
I think the github plugin example doesn't say that we need the original material.js file linked.

I inspected the demo site and it was referenced in the head as a link, so you probably need to link the original material.js.

Whoever is writing this plugin, you may need to add this to your github page.

**Comment by steamonimo** [comment]
Thanks for your comment. In the mean time I have realized that the mdl drawer element can not be nested in a div. I will close the issue. This mdl issue is due to constrains in mdl as you can read here:
https://github.com/google/material-design-lite/issues/1857
